Add sync support for gsm
SpectralOps/teller pull request #105
Opened 2022-05-12 11:38 UTC by guylev008

## Related Issues
#46 

## Description
Added support to:
- delete a secret version
- add a secret version
- get mapping for the latest secrets version

# Checklist
- [X] Tests
- [X] Documentation
- [ ] Linting

2022-05-12 13:34 UTC, kaplanelad requested changes

2022-05-12 14:41 UTC, guylev008 commented on pkg/providers/google_secretmanager.go
> +func (a *GoogleSecretManager) getSecret(path string) (string, error) {
so i'll change all others to recieve a string instead of `kp core.KeyPath`

2022-05-12 15:57 UTC, guylev008 commented on pkg/providers/google_secretmanager.go
>  func (a *GoogleSecretManager) PutMapping(p core.KeyPath, m map[string]string) error {
done

2022-05-16 17:27 UTC, kaplanelad approved these changes

2022-05-16 17:28 UTC, kaplanelad commented
Looks good @guylev008

2022-05-16 17:28 UTC, merged