#83 Added secret file provider
SpectralOps/teller pull request #84
Opened 2022-04-10 09:06 UTC by nazar256

## Related Issues
#83

## Description
Added secret file provider. It maps secret is presented as file containing a secret string (i.e. docker secret mounted into container) into environment variable. For instance, for applications which do not support secret files themselves.

## Motivation and Context
Mounting secrets into docker container is considered as best practice opposed to passing them as environment variables. However only few applications support secret files out of the box.
https://github.com/SpectralOps/teller/issues/83

## How Has This Been Tested?
Tested it manually. For instance with the default config `./teller run env`. Covered with unit tests in similar way as other providers.
Tested in linux_amd64 envoronment manually and with `make test`.
No possible side effects (on other code) is expected.

# Checklist
- [x] Tests
- [x] Documentation
- [x] Linting

2022-04-16 21:07 UTC, kaplanelad requested changes
Hey @nazar256, thanks for adding this provider. 
Can you please check my litter comments?

2022-04-16 21:07 UTC, kaplanelad commented on pkg/providers/secretfile.go
> +func (d *SecretFileReader) Delete(p string) error {
This function in used?

2022-04-16 21:07 UTC, kaplanelad commented on README.md
> +dotenv:
```suggestion
secretfile:
```

2022-05-15 16:39 UTC, nazar256 commented
Already solved by `filesystem` plugin.

2022-05-15 16:39 UTC, closed without merging